---
# tasks file for nginx


- name: Instalacao Nginx
  apt:
    name: nginx
    state: present

- name: Criando Diretorio Personalizado
  shell: mkdir /etc/nginx/wpconf

- name: Copiando general.conf
  template:
    src: general.conf
    dest: /etc/nginx/wpconf/general.conf

- name: Copiando letsencrypt.conf
  template:
    src: letsencrypt.conf
    dest: /etc/nginx/wpconf/letsencrypt.conf

- name: Copiando security.conf
  template:
    src: security.conf
    dest: /etc/nginx/wpconf/security.conf

- name: Copiando wordpress.conf
  template:
    src: wordpress.conf
    dest: /etc/nginx/wpconf/wordpress.conf

- name: Copiando php_fastcgi.conf
  template:
    src: php_fastcgi.conf
    dest: /etc/nginx/wpconf/php_fastcgi.conf

- name: Configurando Vhost
  template:
    src: site.conf
    dest: /etc/nginx/sites-available/{{ dominio_site }}.conf

- name: Ativando Vhost
  file:
    src: /etc/nginx/sites-available/{{ dominio_site }}.conf
    dest: /etc/nginx/sites-enabled/{{ dominio_site }}.conf
    state: link

- name: Conf Amplify
  template:
    src: stub_status.conf
    dest: /etc/nginx/conf.d/stub_status.conf

- name: Diretorio Site
  file:
    path: "{{ diretorio_site }}"
    state: directory
    owner: www-data
    group: www-data

- name: Remocao Vhost Default
  file:
    path: /etc/nginx/sites-enabled/default 
    state: absent  
- name: Remocao Vhost Default
  file:
    path: /etc/nginx/sites-available/default 
    state: absent
  notify: restart nginx

