- hosts: all 
  become: true

  tasks:

    # Nginx Amplify - Monitoramento
    - name: Verificando nginx Amplify
      stat: path=/etc/amplify-agent/
      register: stat_result
    - name: Install Nginx Amplify
      shell: |
          curl -L -O https://github.com/nginxinc/nginx-amplify-agent/raw/master/packages/install.sh
          API_KEY='{{ key_amplify }}' sh ./install.sh
          apt install libfcgi-bin -y             
      when: not stat_result.stat.exists


  # Variaveis personalizaveis / Definicao de dominio, email, usuarios 
  vars_files:
    - /home/projeto/ansible/vars/vars.yml