- hosts: all 
  become: true
  roles:
    - mysql
    - nginx
    - php
    - wordpress

  
  tasks:


    # Instalacao SSL Let's Encrypt
    - name: Verificando SSL
      stat: path=/etc/letsencrypt/live/www.{{diretorio_ssl}}
      register: stat_result
    - name: Instalando SSL
      shell: certbot --nginx -d www."{{ dominio_site }}" -d "{{ dominio_site }}" --non-interactive --agree-tos -m {{ email }}
      when: not stat_result.stat.exists

    # Configuracao de Usuario p/ Site
    - name: Usuario Shell
      ansible.builtin.user:
        name: "{{ user_site }}"
        shell: /bin/bash
        groups: www-data
        home: "{{ diretorio_site }}"
        append: yes
    - name: Permissoes
      shell: chown -R {{ user_site }}:www-data {{ diretorio_site }}

    # Adminer MySQL Tool 
    - name: Tools:: Adminer
      shell: |
            cd {{ diretorio_site }}/ 
            wget https://github.com/vrana/adminer/releases/download/v4.8.0/adminer-4.8.0.php {{ diretorio_site }}/ 
            mv adminer-4.8.0.php adminer.php
            chown -R {{ user_site }}:www-data {{ diretorio_site }}
    
     # Composer
    - name: Verificando Composer
      stat: path=/usr/bin/compose
      register: stat_result
    - name: Install Composer 
      shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      when: not stat_result.stat.exists


  # Variaveis personalizaveis / Definicao de dominio, email, usuarios 
  vars_files:
    - /home/projeto/ansible/vars/vars.yml