- hosts: all 
  become: true
  roles:
    - mysql
    - nginx
    - php
    - wordpress

  
  tasks:

    # Instalacao SSL Let's Encrypt
    - name: Verificando SSL
      stat: path={{ diretorio_ssl }}/
      register: stat_result
    - name: Instalando SSL
      shell: certbot --nginx -d {{ dominio_site }} -d www.{{ dominio_site }} --non-interactive --agree-tos -m {{ email }}
      when: not stat_result.stat.exists

    # Configuracao de Usuario p/ Site 
    - name: Usuario Shell / SFTP
      ansible.builtin.user:
        name: "{{ user_site }}"
        shell: /bin/bash
        groups: www-data
        home: "{{ diretorio_site }}"
        append: yes
        uid: "{{ uid_user }}"
        
    - name: Permissoes Usuario Shell / SFTP
      shell: | 
            chown -R {{ user_site }}:www-data {{ diretorio_site }}/
            chown -R {{ user_site }}:www-data {{ diretorio_site }}/* 
            chown -R {{ user_site }}:www-data {{ diretorio_site }}/. 
            cd {{ diretorio_site }}/
            find . -type f -exec chmod 664 {} + 
            find . -type d -exec chmod 775 {} + 
            
    # Adminer MySQL Tool 
    - name: Tools - Adminer
      shell: |
            cd {{ diretorio_site }}/ 
            wget https://github.com/vrana/adminer/releases/download/v4.8.0/adminer-4.8.0.php {{ diretorio_site }}/ 
            mv adminer-4.8.0.php adminer.php
            chown -R {{ user_site }}:www-data {{ diretorio_site }}
    
     # Composer
    - name: Verificando Composer
      stat: path=/usr/bin/compose
      register: stat_result
    - name: Install Composer 
      shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      when: not stat_result.stat.exists

     # WP CLI
    - name: Verificando WP CLI
      stat: path=/usr/local/bin/wp
      register: stat_result
    - name: Install WP CLI
      shell: |
            curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
            chmod +x wp-cli.phar
            mv wp-cli.phar /usr/local/bin/wp            
      when: not stat_result.stat.exists 

    # Nginx Amplify - Monitoramento
    - name: Verificando nginx Amplify
      stat: path=/etc/amplify-agent/
      register: stat_result
    - name: Install Nginx Amplify
      shell: |
          curl -L -O https://github.com/nginxinc/nginx-amplify-agent/raw/master/packages/install.sh
          API_KEY='{{ key_amplify }}' sh ./install.sh
          apt install libfcgi-bin -y             
      when: not stat_result.stat.exists

    # ClamAV
    - name: Verificando ClamAV
      stat: path=/etc/clamav
      register: stat_result
    - name: Install WP CLI
      shell: |
            apt-get install clamav clamav-daemon -y
            systemctl stop clamav-freshclam
            freshclam
            systemctl start clamav-freshclam
            /etc/init.d/clamav-daemon start            
      when: not stat_result.stat.exists 

    # Restart Servicos
    - name: Restart Servicos 
      shell: |
           /etc/init.d/*-fpm restart
           /etc/init.d/amplify-agent restart


  # Variaveis personalizaveis / Definicao de dominio, email, usuarios 
  vars_files:
    - /home/projeto/ansible/vars/vars.yml