- hosts: all 
  become: true
  roles:
    - mysql
    - ssl
    - nginx
    - php
    - wordpress

  
  tasks:

    # Configuracao de Usuario p/ Site 
    - name: Usuario Shell / SFTP
      ansible.builtin.user:
        name: "{{ user_site }}"
        shell: /bin/bash
        groups: www-data
        home: "{{ diretorio_site }}"
        append: yes
        uid: "{{ uid_user }}"
        
     
    # Adminer MySQL Tool 
    - name: Verificando Adminer
      stat: path={{ diretorio_site }}/adminer.php
      register: stat_result
    - name: Install Adminer 
      shell: |
            cd {{ diretorio_site }}/ 
            wget https://github.com/vrana/adminer/releases/download/v4.8.0/adminer-4.8.0.php {{ diretorio_site }}/ 
            mv adminer-4.8.0.php adminer.php
            chown -R {{ user_site }}:www-data {{ diretorio_site }}
      when: not stat_result.stat.exists

    # Composer
    - name: Verificando Composer
      stat: path=/usr/bin/compose
      register: stat_result
    - name: Install Composer 
      shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      when: not stat_result.stat.exists

    # WP CLI
    - name: Verificando WP CLI
      stat: path=/usr/local/bin/wp
      register: stat_result
    - name: Install WP CLI
      shell: |
            curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
            chmod +x wp-cli.phar
            mv wp-cli.phar /usr/local/bin/wp            
      when: not stat_result.stat.exists 

    - name: Permissoes Usuario Shell / SFTP
      shell: | 
            chown -R {{ user_site }}:www-data {{ diretorio_site }}/ 
            cd {{ diretorio_site }}/
            find . -type f -exec chmod 664 {} + 
            find . -type d -exec chmod 775 {} +
            chmod -R g+w  {{ diretorio_site }}/

    # Redis Cache
    - name: Verificando Redis
      stat: path=/etc/redis
      register: stat_result
    - name: Install Redis
      shell: |
            apt install redis-server -y
            systemctl start redis-server
      when: not stat_result.stat.exists

    # Restart Servicos
    - name: Restart Servicos 
      shell: |
           /etc/init.d/*-fpm restart
           /etc/init.d/nginx restart
           /etc/init.d/redis-server restart 


  # Variaveis personalizaveis / Definicao de dominio, email, usuarios 
  vars_files:
    - /home/projeto/ansible/vars/vars.yml

    