---
# tasks file for wordpress

- name: Download WordPress
  shell: cd {{ diretorio_site }} && wget http://wordpress.org/latest.tar.gz && tar xfz latest.tar.gz && cd wordpress && mv * ../ && cd .. && rm -rf wordpress/ && rm latest.tar.gz && chown -R www-data:www-data .

